from __future__ import annotations

from collections import Counter, deque
from decimal import Decimal
from typing import Literal

from pydantic import Field, field_validator, model_validator

from business_coordinator.domain.models import CanonicalModel, ProcessId, ResourceType

GuardName = Literal[
    "customer_is_active",
    "credit_approved",
    "inventory_is_available",
    "inventory_is_allocated",
    "order_is_packed",
    "shipment_confirmed",
    "payment_received",
    "reorder_approved",
    "purchase_order_approved",
    "supplier_delivery_received",
    "supplier_invoice_matched",
    "supplier_payment_due",
]
OperationalMetric = Literal[
    "object_count",
    "total_quantity",
    "total_monetary_value",
    "backlog_count",
    "average_waiting_time",
    "available_capacity",
    "resource_utilization",
    "exception_count",
    "inventory_quantity",
    "accounts_receivable",
    "accounts_payable",
    "cash",
]
AccountName = Literal[
    "cash",
    "accounts_receivable",
    "accounts_payable",
    "inventory",
    "revenue",
    "cost_of_goods_sold",
    "goods_received_not_invoiced",
]
AmountBasis = Literal["order_amount", "inventory_cost", "supplier_invoice_amount", "payment_amount"]


class TransitionDefinition(CanonicalModel):
    target: str = Field(pattern=r"^[a-z][a-z0-9_]*$")
    guard: GuardName


class FinancialEffectDefinition(CanonicalModel):
    event: str = Field(pattern=r"^[a-z][a-z0-9_]*$")
    debit_account: AccountName
    credit_account: AccountName
    amount_basis: AmountBasis

    @model_validator(mode="after")
    def accounts_are_distinct(self) -> FinancialEffectDefinition:
        if self.debit_account == self.credit_account:
            raise ValueError("debit_account and credit_account must differ")
        return self


class ProcessNodeDefinition(CanonicalModel):
    id: str = Field(pattern=r"^[a-z][a-z0-9_]*$")
    label: str = Field(min_length=1)
    resource: ResourceType
    processing_time_hours: Decimal = Field(gt=0)
    next: tuple[TransitionDefinition, ...] = ()
    events_on_entry: tuple[str, ...] = ()
    events_on_exit: tuple[str, ...] = ()
    operational_metrics: tuple[OperationalMetric, ...] = ()
    financial_effects: tuple[FinancialEffectDefinition, ...] = ()

    @field_validator("events_on_entry", "events_on_exit")
    @classmethod
    def validate_event_names(cls, values: tuple[str, ...]) -> tuple[str, ...]:
        for value in values:
            if (
                not value
                or value != value.lower()
                or not value.replace("_", "a").isalnum()
                or not value[0].isalpha()
            ):
                raise ValueError("event names must use lower_snake_case identifiers")
        if len(values) != len(set(values)):
            raise ValueError("event names must be unique")
        return values

    @model_validator(mode="after")
    def validate_node_metadata(self) -> ProcessNodeDefinition:
        if len(self.operational_metrics) != len(set(self.operational_metrics)):
            raise ValueError("operational metrics must be unique")
        generated_events = set(self.events_on_entry).union(self.events_on_exit)
        effect_events = [effect.event for effect in self.financial_effects]
        unknown_effect_events = sorted(set(effect_events) - generated_events)
        if unknown_effect_events:
            raise ValueError(
                "financial effects reference events not generated by this node: "
                f"{unknown_effect_events}"
            )
        if len(effect_events) != len(set(effect_events)):
            raise ValueError("financial-effect events must be unique within a node")
        return self


class ProcessDefinition(CanonicalModel):
    process_id: ProcessId
    version: int = Field(gt=0)
    label: str = Field(min_length=1)
    initial_node_id: str = Field(pattern=r"^[a-z][a-z0-9_]*$")
    terminal_node_ids: tuple[str, ...] = Field(min_length=1)
    nodes: tuple[ProcessNodeDefinition, ...] = Field(min_length=1)

    @model_validator(mode="after")
    def validate_graph(self) -> ProcessDefinition:
        node_ids = [node.id for node in self.nodes]
        duplicates = sorted(name for name, count in Counter(node_ids).items() if count > 1)
        if duplicates:
            raise ValueError(f"duplicate node IDs: {duplicates}")
        node_id_set = set(node_ids)
        if self.initial_node_id not in node_id_set:
            raise ValueError(f"initial node does not exist: {self.initial_node_id}")
        if len(self.terminal_node_ids) != len(set(self.terminal_node_ids)):
            raise ValueError("terminal node IDs must be unique")
        unknown_terminals = sorted(set(self.terminal_node_ids) - node_id_set)
        if unknown_terminals:
            raise ValueError(f"terminal nodes do not exist: {unknown_terminals}")

        targets: list[str] = []
        adjacency: dict[str, tuple[str, ...]] = {}
        for node in self.nodes:
            node_targets = tuple(transition.target for transition in node.next)
            if len(node_targets) != len(set(node_targets)):
                raise ValueError(f"node {node.id} has duplicate transition targets")
            if node.id in node_targets:
                raise ValueError(f"node {node.id} cannot transition to itself")
            if node.id in self.terminal_node_ids and node_targets:
                raise ValueError(f"terminal node {node.id} cannot have transitions")
            if node.id not in self.terminal_node_ids and not node_targets:
                raise ValueError(f"non-terminal node {node.id} must have a transition")
            adjacency[node.id] = node_targets
            targets.extend(node_targets)

        unknown_targets = sorted(set(targets) - node_id_set)
        if unknown_targets:
            raise ValueError(f"transition targets do not exist: {unknown_targets}")

        reachable = {self.initial_node_id}
        pending = deque([self.initial_node_id])
        while pending:
            for target in adjacency[pending.popleft()]:
                if target not in reachable:
                    reachable.add(target)
                    pending.append(target)
        unreachable = sorted(node_id_set - reachable)
        if unreachable:
            raise ValueError(f"nodes are unreachable from initial node: {unreachable}")
        if not reachable.intersection(self.terminal_node_ids):
            raise ValueError("no terminal node is reachable from the initial node")

        allowed_guards = {
            "order_to_cash": {
                "customer_is_active",
                "credit_approved",
                "inventory_is_available",
                "inventory_is_allocated",
                "order_is_packed",
                "shipment_confirmed",
                "payment_received",
            },
            "procure_to_pay": {
                "reorder_approved",
                "purchase_order_approved",
                "supplier_delivery_received",
                "supplier_invoice_matched",
                "supplier_payment_due",
            },
        }
        configured_guards = {transition.guard for node in self.nodes for transition in node.next}
        invalid_guards = sorted(configured_guards - allowed_guards[self.process_id])
        if invalid_guards:
            raise ValueError(f"guards are not valid for {self.process_id}: {invalid_guards}")
        return self

    def node(self, node_id: str) -> ProcessNodeDefinition:
        for node in self.nodes:
            if node.id == node_id:
                return node
        raise KeyError(f"unknown node for {self.process_id}: {node_id}")

    def transition(self, source: str, target: str) -> TransitionDefinition:
        for transition in self.node(source).next:
            if transition.target == target:
                return transition
        raise ValueError(f"transition is not permitted for {self.process_id}: {source} -> {target}")
